### ISSUE TITLE
Whould you tell us the url of documentation?

### ISSUE THREAD

**Issue by niku** [access-company/antikythera#1]
It seems that it haven't been existed the documentation to the indicated [url](https://hexdocs.pm/antikythera) by CONTRIBUTING.md 😃

**Comment by skirino** [comment]
Right, some links are dead because we haven't yet published the docs to hexdocs.
We'll make them available on-line in the next week.
For the meantime please look at the source code directly or build the docs at your local environment (`$ mix docs`).

**Comment by niku** [comment]
It makes sense. Thanks 👍
